"""user昵称可以为空

Revision ID: 0a6c5e5c4404
Revises: e7ae9a0db4f0
Create Date: 2023-05-19 15:30:14.552817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a6c5e5c4404'
down_revision = 'e7ae9a0db4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickName',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickName',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)

    # ### end Alembic commands ###
