"""取消食谱创建者字段

Revision ID: 1552410edc92
Revises: fb551ae88a8b
Create Date: 2023-05-10 16:40:24.139853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1552410edc92'
down_revision = 'fb551ae88a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('recipe_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
