"""将user和amdin分开

Revision ID: 238b1d0cb936
Revises: 453e7bdaebb5
Create Date: 2023-05-20 13:33:01.955326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '238b1d0cb936'
down_revision = '453e7bdaebb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('roles_users_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('fs_uniquifier')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('active')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index('fs_uniquifier', ['fs_uniquifier'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_users_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('admin_id')

    op.drop_table('admin')
    # ### end Alembic commands ###
