"""小修改

Revision ID: 35f5f428767d
Revises: f33bfe148dab
Create Date: 2023-05-13 19:38:54.505422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35f5f428767d'
down_revision = 'f33bfe148dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('taste')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taste', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.add_column(sa.Column('difficulty', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))

    # ### end Alembic commands ###
