"""修改recipe主键类型

Revision ID: 3fb2847720dc
Revises: 1552410edc92
Create Date: 2023-05-13 19:35:12.736224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fb2847720dc'
down_revision = '1552410edc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
