"""修改Ingredient主键类型3

Revision ID: 453e7bdaebb5
Revises: 2882c6c27ee7
Create Date: 2023-05-20 13:23:01.087050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453e7bdaebb5'
down_revision = '2882c6c27ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.String(length=200), nullable=False))
        batch_op.create_foreign_key(None, 'ingredient', ['ingredient_id'], ['id'])

    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.String(length=200), nullable=False))
        batch_op.create_foreign_key(None, 'ingredient', ['ingredient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###
