"""用户，食材，交互表

Revision ID: 527cad2c4da1
Revises: 
Create Date: 2023-05-08 16:44:20.703640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527cad2c4da1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ingredient_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ingredient', ['ingredient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ingredient_id')
        batch_op.drop_column('quality')

    op.drop_table('user_ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
