"""把season表删除

Revision ID: 797994a14058
Revises: fa61a6166a2e
Create Date: 2023-05-20 13:01:49.747407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '797994a14058'
down_revision = 'fa61a6166a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    op.drop_table('ingredient_area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_area',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('Ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Area_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Area_id'], ['area.id'], name='ingredient_area_ibfk_1'),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], name='ingredient_area_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('area',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
