"""userModel允许avatarUrl和openid为空

Revision ID: 835045539663
Revises: 35f5f428767d
Create Date: 2023-05-17 13:08:23.048406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '835045539663'
down_revision = '35f5f428767d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatarUrl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)
        batch_op.alter_column('openid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('openid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)
        batch_op.alter_column('avatarUrl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=False)

    # ### end Alembic commands ###
