"""食材

Revision ID: 93d5bb8ed823
Revises: b932476f3fa2
Create Date: 2023-05-10 14:00:08.180728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d5bb8ed823'
down_revision = 'b932476f3fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=200), nullable=True),
    sa.Column('Ingredient_id', sa.Integer(), nullable=False),
    sa.Column('Area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('subcategory')
        batch_op.drop_column('category')

    op.drop_table('ingredient_area')
    op.drop_table('area')
    # ### end Alembic commands ###
