"""在ingredient中添加orders

Revision ID: bcdce6357073
Revises: 238b1d0cb936
Create Date: 2023-05-20 20:32:45.436535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcdce6357073'
down_revision = '238b1d0cb936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('quality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))

    # ### end Alembic commands ###
