"""食谱

Revision ID: d54f8bc35c89
Revises: 93d5bb8ed823
Create Date: 2023-05-10 14:03:38.347364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54f8bc35c89'
down_revision = '93d5bb8ed823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('process', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('time_consuming', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
