"""补充食谱 难度和口味

Revision ID: fb551ae88a8b
Revises: d54f8bc35c89
Create Date: 2023-05-10 14:47:32.494008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb551ae88a8b'
down_revision = 'd54f8bc35c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taste', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('taste')

    # ### end Alembic commands ###
