"""修改Ingredient主键类型1

Revision ID: fc129d49ae48
Revises: 797994a14058
Create Date: 2023-05-20 13:22:04.940644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc129d49ae48'
down_revision = '797994a14058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_2', type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('user_ingredient_ibfk_1', type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_ingredient_ibfk_1', 'ingredient', ['ingredient_id'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('order_item_ibfk_2', 'ingredient', ['ingredient_id'], ['id'])

    # ### end Alembic commands ###
